exec-once = xrandr --output $mainmon --primary
exec-once = xrdb -merge ~/.Xresources
exec-once = hyprctl setcursor "capitaine-cursors" 24
exec-once = signal-desktop
# exec-once = $scripts/close_refocus_fix 2>&1 > /dev/null
exec-once = pkill -x hypridle; hypridle
