#!/bin/bash
# System ~~~~~~~~~~~~~~~~~~~~~~~~~
ckb-next --background &
i3lock -i ~/.config/misc/flock.png &
setxkbmap fr
numlockx on 
sxhkd &
compton -b &

xsetroot -cursor_name left_ptr &
xset s off -dpms &
xset r rate 250 75 &
#nvidia-settings --load-config-only --assign="SyncToVBlank=0" & #Unlimited Framerate
xrdb ~/.Xresources
#Others ---------------------
conky -q &
nm-applet &
mpd &
# APPS ~~~~~~~~~~~~~~~~~
megasync &
discord-canary &
looking-glass-client -s &
optirun true &
#~/bin/Software/mpd_discord_richpresence &
