#!/bin/bash
source ~/bin/wpc # To use $mainpc and $laptop
# Exec ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
if [[ $(pgrep -c sxhkd) -eq 0 ]]
then
	~/.config/bspwm/scripts/autostart
fi
~/.fehbg &
~/.config/polybar/launch.sh &
~/.config/bspwm/scripts/redo &
# End Exec ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bspc rule -r $(bspc rule -l)
case $PC in
	mainpc)
		bspc monitor HDMI1  -d 1 2 3 4
		bspc monitor HDMI2  -d 5 6 7 8 9 10
		bspc config border_width         1
		bspc config window_gap           8
		;;
	laptop)
		bspc config border_width         2
		bspc config window_gap           12
		;;
esac

bspc config normal_border_color "#500000"
bspc config active_border_color "#600000"
bspc config focused_border_color "#bb0000"

bspc config presel_feedback_color "#100000"
bspc config split_ratio         0.5
bspc config click_to_focus 	button1	

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle 	true

bspc config ignore_ewmh_focus	true
bspc config directional_focus_tightness low

case $PC in
	mainpc)
		#bspc rule -a Chromium desktop=5 follow=on
		bspc rule -a Firefox desktop=5 follow=on
		bspc rule -a discord desktop='^1'
		bspc rule -a qBittorrent desktop='2' follow=on
		bspc rule -a skypeforlinux desktop='1'
		bspc rule -a Lxappearance state=floating follow=on
		bspc rule -a Pavucontrol state=floating follow=on
		bspc rule -a 'Gimp-2.8' state=floating desktop=8 follow=on
		bspc rule -a 'VESC Tool' desktop=8 follow=on
		bspc rule -a Screenkey manage=off
		bspc rule -a 'Ethereum Wallet' desktop=3 state=floating follow=on
		bspc rule -a Ethereumwallet desktop=3 state=floating follow=on
		bspc rule -a vscode-color-ui state=floating follow=on
		bspc rule -a Virt-manager desktop=3 follow=on
		bspc rule -a looking-glass-client desktop=8 follow=on
		;;
	laptop)
		# If docked
		if [ `xrandr | grep -c "^DP1 connected"` -gt 0 ] 
		then
			bspc monitor eDP1  -d 1 2 3 4
			bspc monitor DP1   -d 5 6 7 8 9 10
			#bspc rule -a Chromium desktop=5 follow=on
                        bspc rule -a Firefox desktop=5 follow=on
			bspc rule -a discord desktop='^1'
			bspc rule -a qBittorrent desktop='2' follow=on
			bspc rule -a skypeforlinux desktop='3'
			bspc rule -a Lxappearance state=floating follow=on
			bspc rule -a Pavucontrol state=floating follow=on
			bspc rule -a 'Gimp-2.8' state=floating desktop=8 follow=on
			bspc rule -a Screenkey manage=off
			bspc rule -a 'Ethereum Wallet' desktop=3 state=floating follow=on
			bspc rule -a Ethereumwallet desktop=3 state=floating follow=on
			bspc rule -a vscode-color-ui state=floating follow=on
			~/bin/dock
		else
			bspc monitor eDP1  -d 1 2 3 4 5 6 7 8 9 10
			#bspc rule -a Chromium desktop=1 follow=on
			bspc rule -a Firefox desktop=1 follow=on
			bspc rule -a discord desktop='^10'
			bspc rule -a qBittorrent desktop='9' follow=on
			bspc rule -a skypeforlinux desktop='10'
			bspc rule -a Lxappearance state=floating follow=on
			bspc rule -a Pavucontrol state=floating follow=on
			bspc rule -a 'Gimp-2.8' state=floating desktop=8 follow=on
			bspc rule -a Screenkey manage=off
			bspc rule -a 'Ethereum Wallet' desktop=3 state=floating follow=on
			bspc rule -a Ethereumwallet desktop=3 state=floating follow=on
			bspc rule -a vscode-color-ui state=floating follow=on
			xrdb ~/.Xresources
			xrdb -merge <(echo "Xft.dpi: 180")
			xrdb -merge <(echo "rofi.font: sans-serif bold 30")

		fi
		;;
esac
