#!/usr/bin/env bash
# System ~~~~~~~~~~~~~~~~~~~~~~~~~
$mainpc && (ckb-next -b &)
$mainpc && i3lock -n -i ~/.config/etc/flock.png & #  && ./.wall &
$laptop && i3lock -i ~/.config/etc/flocklap.png &
setxkbmap fr
numlockx on
$mainpc && sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc ~/.config/bspwm/sxhkd/mainpc &
$laptop && sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc ~/.config/bspwm/sxhkd/laptop &
compton -b &

xsetroot -cursor_name left_ptr &
xset s off -dpms &
$laptop && xss-lock -q ~/bin/lock &
xset r rate 250 75 &

xrdb ~/.Xresources
$laptop && xrdb -merge <(echo "Xft.dpi: 180")
$laptop && xrdb -merge <(echo "rofi.font: sans-serif bold 30")

#$mainpc && nvidia-settings --load-config-only --assign="SyncToVBlank=0" & #Unlimited Framerate
setxkbmap -option "lv3:caps_switch" &
#Others ---------------------
$laptop && unclutter --timeout 3 -b &
$mainpc && conky -q &
nm-applet &
(pkill -x mpd;mpd) &
# APPS ~~~~~~~~~~~~~~~~~
megasync &
$mainpc && (discord-canary || discord || Discord) &
$mainpc && optirun true &
#$mainpc && /bin/Software/mpd_discord_richpresence &
~/.wall &
