#!/bin/bash
# System ~~~~~~~~~~~~~~~~~~~~~~~~~
$mainpc && ckb-next --background &
i3lock -i ~/.config/misc/flock.png &
setxkbmap fr
numlockx on
$mainpc && sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc ~/.config/bspwm/sxhkd/mainpc &
$laptop && sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc ~/.config/bspwm/sxhkd/laptop &
compton -b &

xsetroot -cursor_name left_ptr &
xset s off -dpms &
$laptop && xss-lock -q ~/bin/lock &
xset r rate 250 75 &
#$mainpc && nvidia-settings --load-config-only --assign="SyncToVBlank=0" & #Unlimited Framerate
$laptop && setxkbmap -option "lv3:caps_switch" &
xrdb ~/.Xresources
#Others ---------------------
$laptop && unclutter --timeout 3 -b &
$mainpc && conky -q &
nm-applet &
mpd &
# APPS ~~~~~~~~~~~~~~~~~
megasync &
$mainpc && discord-canary &
$mainpc && optirun true &
$laptop && `sleep 3; ~/.config/bspwm/redo` &
#$mainpc && /bin/Software/mpd_discord_richpresence &
