#!/bin/bash
setxkbmap fr
$laptop && setxkbmap -option "lv3:caps_switch" &
numlockx on
xsetroot -cursor_name left_ptr &
xset s off -dpms &
xset r rate 250 75 &
$mainpc && xmodmap -e "keycode 66 = ISO_Level3_Shift"
#$mainpc && optirun nvidia-settings --load-config-only --assign="SyncToVBlank=1" & #Unlimited Framerate
xrdb ~/.Xresources
$laptop && xrdb -merge <(echo "Xft.dpi: 180")
$laptop && xrdb -merge <(echo "rofi.font: sans-serif bold 30")
